### ISSUE TITLE
Improved error messaging when adding remotes in `dee`

### ISSUE THREAD

**Issue by CluEleSsUK** [thibmeu/drand-rs#1]
A very small nitpick but I noticed the following scenarios provide confusing error messages:
- adding a remote without passing a scheme (eg `https://`)
- adding a remote with a trailing slash

Loving `dee` though!! Gonna save me so much time ctrl-Ring for chain hashes!
I'd also be happy to pick this issue up, but probably not until next week sometime

**Comment by thibmeu** [comment]
Thanks for reporting. The upstream version should address these concerns.

You can try with `cargo install dee --git https://github.com/thibmeu/drand-rs`.
