### ISSUE TITLE
hash_to_curve on g1 and g2

### ISSUE THREAD

**Issue by nsoroush** [thibmeu/drand-rs#12]
HI, I am using the bls_verify for the data that  I got from "https://api3.drand.sh/dbd506d6ef76e5f386f41c651dcb808c5bcbd75471cc4eafa3f4df7ad4e4c493/public/1" and I got error. I was wondering wheather I am making a mistake or the hash_to_curev should be define in a different ways for G1 and G2.

**Comment by thibmeu** [comment]
Do you have some example code that reproduces this problem? G1/G2 hash to curve changed with the RFC9380 introduction (in [drand_core 0.0.13](https://github.com/thibmeu/drand-rs/blob/main/drand_core/CHANGELOG.md#0013---2023-08-23)).

There is an example usage available on the [documentation](https://docs.rs/drand_core/0.0.14/drand_core/#usage).

With drand_core 0.0.14, the example against the remote you mention successfully pass validation.
Full code with the modification

```rust
use drand_core::HttpClient;

fn main() {
    const ROUND: u64 = 1;

    let client: HttpClient = "https://api3.drand.sh/dbd506d6ef76e5f386f41c651dcb808c5bcbd75471cc4eafa3f4df7ad4e4c493".try_into().unwrap();
    let beacon = client.get(ROUND).unwrap();

    println!("{:?}", beacon);
}
```

**Comment by thibmeu** [comment]
@nsoroush are you still seeing an issue?

**Comment by thibmeu** [comment]
Close for inactivity.
